services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - db_user_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_net
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_net
    depends_on:
      - wordpress
    restart: always

networks:
  inception_net:

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ruidos-s/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ruidos-s/data/wordpress

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt